name: Android CI

on:
  push:
    branches:
        - '*'
        - '!master'
        - '!release*'
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit tests
      run: ./gradlew test --console=plain
      
  apk:
    name: Generate apk
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit tests
      run: ./gradlew build --console=plain
    - name: Save apk
      uses: actions/upload-artifact@v2
      with:
        name: Application
        path: app/build/outputs/apk/debug/app-debug.apk

